-- CreateTable
CREATE TABLE "Print" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "file" BLOB NOT NULL,
    "printed" BOOLEAN NOT NULL DEFAULT false
);
